import { Crown, Sparkles, Zap } from "lucide-react"

export const plans = [
  {
    name: "Free",
    icon: Sparkles,
    monthlyPrice: 0,
    yearlyPrice: 0,
    period: "",
    description: "Perfect for testing and small projects.",
    tokens: 1000,
    pricePerExcess: 0.05,
    features: ["1,000 successful verifications per month", "Basic support"],
    cta: "Start Free",
    popular: false,
    isRecommended: false,
    order: 0,
    id: null,
  },
  {
    name: "Pro",
    icon: Zap,
    monthlyPrice: 100,
    yearlyPrice: 80,
    period: "/month",
    description: "Ideal for growing projects.",
    tokens: 10000,
    pricePerExcess: 0.02,
    features: [
      "10,000 successful verifications per month",
      "community support",
      " $0.02 per successful verification after the first 10,000",
    ],
    cta: "Upgrade to Pro",
    popular: true,
    isRecommended: true,
    order: 1,
    id: 1,
  },
  {
    name: "Premium",
    icon: Crown,
    monthlyPrice: 500,
    yearlyPrice: 400,
    period: "/month",
    description: "Best for enterprise projects.",
    tokens: 100000,
    pricePerExcess: 0.01,
    features: [
      "100,000 successful verifications per month",
      "Excess tokens at $0.01 each",
      "Premium support",
      "Custom branding",
    ],
    cta: "Upgrade to Premium",
    popular: false,
    isRecommended: false,
    order: 2,
    id: 2,
  },
]
